### ISSUE TITLE
3.1话和31话会被认为是同一话的问题。

### ISSUE THREAD

**Issue by 29CC** [sweetnotice/copymanga_downloader#1]
有些漫画会将一话分成几话，写作3.1,3.2这样，由于软件把小数点这样的符号都省略掉了，结果下载后就显示为31,32，之后到了真正的31,32话就会自动跳过去。

**Comment by sweetnotice** [comment]
抱歉,这么久才给您回复
此bug已经在 最新提交中修复[d002ea](https://github.com/sweetnotice/copymanga_downloader/commit/d002ea5926f14cb150b86c9e81f66064814d77c6)
因为好久没看漫画了,软件也很久没用过了,代码也是.我都忘了我当初写那个格式化特殊字符的用途了
:(
