### ISSUE TITLE
大佬，输入pip install -r requirements.txt显示pip文件不存在

### ISSUE THREAD

**Issue by Non-moGam** [sweetnotice/copymanga_downloader#3]

**Comment by sweetnotice** [comment]
你下载的是最新版吗，兄弟好好读读食用指南

**Comment by Non-moGam** [comment]
是最新的吧，包里有这个requirements.txt的文件，还是说是“在当前窗口打开cmd”这里出问题了

**Comment by sweetnotice** [comment]
在文件根目录上方地址栏键入 `cmd`  回车

**Comment by Non-moGam** [comment]
还是不行啊大佬
![image](https://github.com/user-attachments/assets/57c86762-3fe5-4224-ac85-8872ed93d2b2)

**Comment by sweetnotice** [comment]
哇,哥们你这是连python都没装  :( 
去这里[python](https://www.python.org/)找到版本进行下载
推荐下载 3.10 的

**Comment by Non-moGam** [comment]
![image](https://github.com/user-attachments/assets/a687b3ea-7e36-4769-9cb5-36ded0c61d78)
呜哇还是不行啊

**Comment by Non-moGam** [comment]
![image](https://github.com/user-attachments/assets/57d5e8a8-050f-4b43-93d2-d2eaa48d27bb)
刚好像没装好，现在是这样了

**Comment by Non-moGam** [comment]
哦哦好了，谢谢大佬

**Comment by Non-moGam** [comment]
![image](https://github.com/user-attachments/assets/45fe9e15-68b0-4bfa-93cc-9e62accdf845)
斯

**Comment by sweetnotice** [comment]
斯~，你这个是下载路径转义错误，有两种解决办法
1. 使用 双斜杠 `\\` 进行转义 改成 `D:\\liu lan qi downlord` 
2. 使用左斜杠 `/` 改成  `D:/liu lan qi downlord`
